theme = "ayu_evolve"

[keys.normal]
D = "@vgld"
"0" = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
"X" = "extend_line_above"

[keys.select]
"0" = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"

[editor]
default-yank-register = "+"

[editor.lsp]
display-inlay-hints = true

[editor.file-picker]
hidden = false
