# Site-specific additions and overrides for usr.bin.firefox.
# Allow Firefox XDG profile path under ~/.config/mozilla/firefox.
owner @{HOME}/.config/mozilla/ rw,
owner @{HOME}/.config/mozilla/firefox/ rw,
owner @{HOME}/.config/mozilla/firefox/** rwk,

# Allow Wayland proxy socket creation used by Firefox.
owner /run/user/*/wayland-proxy-* rwc,
